Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName : idIndex
          KeySchema :
            - AttributeName: id
              KeyType: HASH
          Projection : 
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}

  Grades:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-grades
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  
  Unverified:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-unverified
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  
  Groups:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-groups
      AttributeDefinitions:
        - AttributeName: group_id
          AttributeType: S
        - AttributeName: owner
          AttributeType: S
      KeySchema:
        - AttributeName: group_id
          KeyType: HASH
        - AttributeName: owner
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName : ownerIndex
          KeySchema :
            - AttributeName: owner
              KeyType: HASH
            - AttributeName: group_id
              KeyType: RANGE
          Projection : 
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
  
  Subjects:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-subjects
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S  
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Schedule:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-schedule
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: day
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: day
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Events:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-events
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName : queryIndex
          KeySchema :
            - AttributeName: id
              KeyType: HASH
            - AttributeName: event_id
              KeyType: RANGE
          Projection : 
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
  FirstLessonNotifications:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-first-lesson-notifications
      AttributeDefinitions:
        - AttributeName: time
          AttributeType: N
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: time
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName : userIDIndex
          KeySchema :
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: time
              KeyType: RANGE
          Projection : 
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}