Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s-org-users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Grades:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s-org-grades
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Events:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s-org-events
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Subjects:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s-org-subjects
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Schedules:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s-org-schedules
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: day
          AttributeType: N
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: day
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  
  Unverified:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s-org-unverified
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  
  Groups:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-groups
      AttributeDefinitions:
        - AttributeName: group_id
          AttributeType: S
        - AttributeName: owner
          AttributeType: S
      KeySchema:
        - AttributeName: group_id
          KeyType: HASH
        - AttributeName: owner
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        IndexName : ownerIndex
        KeySchema :
          - AttributeName: owner
            KeyType: HASH
          - AttributeName: group_id
            KeyType: RANGE
        Projection : 
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
  
  NewSubjects:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-subjects
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S  
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  NewSchedules:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-schedule
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: day
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: day
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  NewEvents:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plannerix-events
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        IndexName : queryIndex
        KeySchema :
          - AttributeName: id
            KeyType: HASH
          - AttributeName: event_id
            KeyType: RANGE
        Projection : 
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}